version: '3.8'
services:
  php-apache-environment:
    image: andripakel02/uas
    container_name: php-apache
    depends_on:
      - db
    volumes:
      - ./pos_php_mysql/:/var/www/html/
    ports:
      - 8090:80
    networks:
      - backend

  db:
    container_name: db_pos
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: _Admin02
      MYSQL_USER: admin
      MYSQL_PASSWORD: _Admin02
      MYSQL_DATABASE: dbpos.sql
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./pos_php_mysql/dbpos.sql:/docker-entrypoint-initdb.d/dbpos.sql
    networks:
      - backend

volumes:
  db:

networks:
  backend:
    name: backend-network
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
